### ISSUE TITLE
App crashes unexpectedly when entering new segmentation

### ISSUE THREAD

**Issue by charlessillett** [CemrgDevelopers/CemrgApp#29]
### Prerequisites

Put an X between the brackets (without spaces [X]) on the following lines if you have done all of the following:

* [X] Checked the wiki board for common solutions: <https://github.com/CemrgAppDevelopers/CemrgApp/wiki>
* [X] Checked that your issue isn't already filed: <https://github.com/search?q=+is%3Aissue+user%3ACemrgAppDevelopers>
* [] Are you providing the log? <https://github.com/CemrgAppDevelopers/CemrgApp/wiki/Troubleshooting>

### Description

CemrgApp unexpectedly closes when making a new segmentation on Step 3 of the Morphological Measurements Pipeline. Specifically, the app closes on clicking 'OK' to enter the name for the new segmentation.

### Steps to Reproduce

1. Load CT image in nii format via Open File
2. Select Morphological Measurements Pipeline
3. Click Step 3: Segment
4. Resize the split between the right hand side segmentation panel and the viewing 4-panels on the left hand side.
5. Click New on the segmentation panel
6. Enter name for segmentation
7. Click "OK" to confirm name 

**Expected behaviour:**

Allow me to begin making my new named segmentation on the loaded CT image.
 
**Actual behavior:**

App closes

**Reproduces how often:**

Does not reproduce on immediately reopening the app. However, on reopening there is significant lag with cursor movement over the CT image. The lag is quite bad when trying to move the 3 different planes of viewing which makes it difficult to segment the image.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue. 
´´´

**Comment by OrodRazeghi** [comment]
A similar issue was also reported originally in #17.

**Comment by angela337** [comment]
This issue is due to the rotation of the MR image. 
Cemrg doesn't seem to know how to deal with this. I was having the same issue just trying to reinit the image. Why this occurs with the segmentation tool as well is that when you create a new segmentation it reinits the image space to be in-plane with your image. 

The rotation information in the nifti header (nii.hdr.hist) reads: 
      quatern_b: -0.0200
      quatern_c: 0.4984
      quatern_d: -0.7342

When I reset these values to [0,0,1], Cemrg no longer crashes. But we lose the original spatial information so this issue will still need to be dealt with.

**Comment by angela337** [comment]
The crash seems to be the same issue as MITK: [https://phabricator.mitk.org/T25682](https://phabricator.mitk.org/T25682). This was resolved in https://phabricator.mitk.org/source/mitk/branches/T25682-DominantAxesError/

So if we are building CemrgApp, we can use this branch of MITK2018 instead rather than checking out MITK2018.04.2 
`git checkout T25682-DominantAxesError `

**Comment by alonsoJASL** [comment]
This should have been fixed on mitk2021. We just need to merge branch `feature/update-mitk` to `development` (and to `master`) whenever possible.

**Comment by alonsoJASL** [comment]
Made a new error #60. Closing this.
